package ca.ulaval.glo2004.domain;

public enum TypeComposante {
    HAYON,
    MUR_SEPARATEUR,
    PLANCHER,
    POUTRE_ARRIERE,
    RESSORTS,
    TOIT,
    MUR_BRUTE,
    AIDE_DESIGN,
    OUVERTURE_LATERALE,
    PROFIL_BEZIER,
    PROFIL_ELLIPSE,
    CONTREPLAQUE_EXTERIEUR,
    CONTREPLAQUE_INTERIEUR
}
